#include <plug_common.h>

#ifdef __cplusplus
extern "C" {
#endif

extern void register_defines(lua_State* L);
extern void register_enums(lua_State* L);
extern void register_global_functions(lua_State* L);

	
	
int PLUG_EXPORT luaopen_osg(lua_State* L) {
	luna_open(L);

	luna_pushModule(L,"osg");
	Luna< osg::AnimationPath::ControlPoint >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::CameraManipulator::CoordinateFrameCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::Object >::Register(L);
	Luna< osg::Camera::DrawCallback >::Register(L);
	Luna< osg::Drawable::DrawCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::EdgeCollector::Edgeloop >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgUtil::EdgeCollector::Edge > > >::Register(L);
	Luna< osg::Drawable::EventCallback >::Register(L);
	Luna< osg::ClampColor::Extensions >::Register(L);
	Luna< osg::BlendColor::Extensions >::Register(L);
	Luna< osg::BlendEquation::Extensions >::Register(L);
	Luna< osg::BlendFunc::Extensions >::Register(L);
	Luna< osg::Drawable::Extensions >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgText");
	Luna< osgText::Font::FontImplementation >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< GLUtesselator >::Register(L);
	Luna< osg::KdTree::LineSegmentIntersection >::Register(L);
	Luna< std::vector< unsigned int > >::Register(L);
	Luna< osg::BufferData::ModifiedCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ExternalFileWriter::ObjectData >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::ArgumentParser::Parameter >::Register(L);
	Luna< osg::PagedLOD::PerRangeData >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ImageOptions::PixelWindow >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::EdgeCollector::Point >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::Program::ProgramBinary >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ImageOptions::RatioWindow >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IntersectionVisitor::ReadCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ReaderWriter::ReadResult >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::GraphicsContext::ResizedCallback >::Register(L);
	Luna< osg::GraphicsContext::ScreenIdentifier >::Register(L);
	Luna< osg::GraphicsContext::ScreenSettings >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::RenderBin::SortCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::GraphicsContext::SwapCallback >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ImageOptions::TexCoordRange >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::Texture::TextureObject >::Register(L);
	Luna< osg::Texture::TextureObjectManager >::Register(L);
	Luna< osg::Texture::TextureObjectSet >::Register(L);
	Luna< osg::Texture::TextureProfile >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::GUIEventAdapter::TouchData >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osgGA::GUIEventAdapter::TouchData::TouchPoint > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::GUIEventAdapter::TouchData::TouchPoint >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::GraphicsContext::Traits >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::EdgeCollector::Triangle >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::KdTree::Triangle >::Register(L);
	Luna< osg::Program::UniformBlockInfo >::Register(L);
	Luna< osg::Drawable::UpdateCallback >::Register(L);
	Luna< osg::StateAttributeCallback >::Register(L);
	Luna< osg::Image::UpdateCallback >::Register(L);
	Luna< osg::View::Slave::UpdateSlaveCallback >::Register(L);
	Luna< osg::Geometry::Vec3ArrayData >::Register(L);
	Luna< osg::GraphicsContext::WindowingSystemInterface >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ReaderWriter::WriteResult >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgViewer");
	Luna< osgViewer::ScreenCaptureHandler::CaptureOperation >::Register(L);
	Luna< osgViewer::ScreenCaptureHandler::WriteToFile >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"OpenThreads");
	Luna< OpenThreads::Atomic >::Register(L);
	Luna< OpenThreads::AtomicPtr >::Register(L);
	Luna< OpenThreads::Barrier >::Register(L);
	Luna< OpenThreads::Block >::Register(L);
	Luna< OpenThreads::BlockCount >::Register(L);
	Luna< OpenThreads::Condition >::Register(L);
	Luna< OpenThreads::ReadWriteMutex >::Register(L);
	Luna< OpenThreads::ScopedReadLock >::Register(L);
	Luna< OpenThreads::ScopedWriteLock >::Register(L);
	Luna< OpenThreads::ReentrantMutex >::Register(L);
	Luna< OpenThreads::Thread >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osg::TemplateIndexArray< signed char, osg::Array::ByteArrayType, 1, GL_BYTE > >::Register(L);
	Luna< osg::TemplateIndexArray< short, osg::Array::ShortArrayType, 1, GL_SHORT > >::Register(L);
	Luna< osg::TemplateIndexArray< int, osg::Array::IntArrayType, 1, 0x1404 > >::Register(L);
	Luna< osg::TemplateIndexArray< unsigned char, osg::Array::UByteArrayType, 1, GL_UNSIGNED_BYTE > >::Register(L);
	Luna< osg::TemplateIndexArray< unsigned short, osg::Array::UShortArrayType, 1, GL_UNSIGNED_SHORT > >::Register(L);
	Luna< osg::TemplateIndexArray< unsigned int, osg::Array::UIntArrayType, 1, 0x1405 > >::Register(L);
	Luna< osg::TemplateArray< float, osg::Array::FloatArrayType, 1, GL_FLOAT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4ub, osg::Array::Vec4ubArrayType, 4, GL_UNSIGNED_BYTE > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2s, osg::Array::Vec2sArrayType, 2, GL_SHORT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3s, osg::Array::Vec3sArrayType, 3, GL_SHORT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4s, osg::Array::Vec4sArrayType, 4, GL_SHORT > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2b, osg::Array::Vec2bArrayType, 2, GL_BYTE > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3b, osg::Array::Vec3bArrayType, 3, GL_BYTE > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4b, osg::Array::Vec4bArrayType, 4, GL_BYTE > >::Register(L);
	Luna< osg::TemplateArray< double, osg::Array::DoubleArrayType, 1, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec2d, osg::Array::Vec2dArrayType, 2, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec3d, osg::Array::Vec3dArrayType, 3, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Vec4d, osg::Array::Vec4dArrayType, 4, 0x140A > >::Register(L);
	Luna< osg::TemplateArray< osg::Matrixf, osg::Array::MatrixArrayType, 16, GL_FLOAT > >::Register(L);
	Luna< osg::BoundingBoxImpl< osg::Vec3f > >::Register(L);
	Luna< osg::BoundingBoxImpl< osg::Vec3d > >::Register(L);
	Luna< osg::BoundingSphereImpl< osg::Vec3f > >::Register(L);
	Luna< osg::BoundingSphereImpl< osg::Vec3d > >::Register(L);
	Luna< std::list< osg::ref_ptr< osg::GLBufferObject > > >::Register(L);
	Luna< std::pair< double, double > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Node > > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Image > > >::Register(L);
	Luna< osg::MixinVector< int > >::Register(L);
	Luna< osg::MixinVector< unsigned char > >::Register(L);
	Luna< osg::MixinVector< unsigned short > >::Register(L);
	Luna< osg::MixinVector< unsigned int > >::Register(L);
	Luna< std::vector< osg::ShaderComponent * > >::Register(L);
	Luna< std::vector< osg::ShadowVolumeOccluder > >::Register(L);
	Luna< osg::Matrix2Template< float > >::Register(L);
	Luna< osg::Matrix2x3Template< float > >::Register(L);
	Luna< osg::Matrix2x4Template< float > >::Register(L);
	Luna< osg::Matrix3x2Template< float > >::Register(L);
	Luna< osg::Matrix3x4Template< float > >::Register(L);
	Luna< osg::Matrix4x2Template< float > >::Register(L);
	Luna< osg::Matrix4x3Template< float > >::Register(L);
	Luna< osg::Matrix2Template< double > >::Register(L);
	Luna< osg::Matrix2x3Template< double > >::Register(L);
	Luna< osg::Matrix2x4Template< double > >::Register(L);
	Luna< osg::Matrix3x2Template< double > >::Register(L);
	Luna< osg::Matrix3x4Template< double > >::Register(L);
	Luna< osg::Matrix4x2Template< double > >::Register(L);
	Luna< osg::Matrix4x3Template< double > >::Register(L);
	Luna< osg::TemplateValueObject< std::string > >::Register(L);
	Luna< osg::TemplateValueObject< bool > >::Register(L);
	Luna< osg::TemplateValueObject< char > >::Register(L);
	Luna< osg::TemplateValueObject< unsigned char > >::Register(L);
	Luna< osg::TemplateValueObject< short > >::Register(L);
	Luna< osg::TemplateValueObject< unsigned short > >::Register(L);
	Luna< osg::TemplateValueObject< int > >::Register(L);
	Luna< osg::TemplateValueObject< unsigned int > >::Register(L);
	Luna< osg::TemplateValueObject< float > >::Register(L);
	Luna< osg::TemplateValueObject< double > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec2f > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec3f > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec4f > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec2d > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec3d > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Vec4d > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Quat > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Plane > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Matrixf > >::Register(L);
	Luna< osg::TemplateValueObject< osg::Matrixd > >::Register(L);
	Luna< std::vector< osg::StateSet const * > >::Register(L);
	Luna< osg::StateAttribute >::Register(L);
	Luna< osg::AlphaFunc >::Register(L);
	Luna< osg::AnimationPath >::Register(L);
	Luna< std::map< double, osg::AnimationPath::ControlPoint > >::Register(L);
	Luna< osg::NodeCallback >::Register(L);
	Luna< osg::AnimationPathCallback >::Register(L);
	Luna< osg::ApplicationUsage >::Register(L);
	Luna< std::map< std::string, std::string > >::Register(L);
	Luna< osg::ApplicationUsageProxy >::Register(L);
	Luna< osg::ArgumentParser >::Register(L);
	Luna< std::map< std::string, osg::ArgumentParser::ErrorSeverity > >::Register(L);
	Luna< osg::BufferData >::Register(L);
	Luna< osg::Array >::Register(L);
	Luna< osg::IndexArray >::Register(L);
	Luna< osg::ArrayVisitor >::Register(L);
	Luna< osg::ConstArrayVisitor >::Register(L);
	Luna< osg::ValueVisitor >::Register(L);
	Luna< osg::ConstValueVisitor >::Register(L);
	Luna< osg::AttributeDispatch >::Register(L);
	Luna< osg::ArrayDispatchers >::Register(L);
	Luna< osg::AudioSink >::Register(L);
	Luna< osg::AudioStream >::Register(L);
	Luna< osg::Node >::Register(L);
	Luna< osg::Group >::Register(L);
	Luna< osg::Transform >::Register(L);
	Luna< osg::AutoTransform >::Register(L);
	Luna< osg::Geode >::Register(L);
	Luna< osg::Billboard >::Register(L);
	Luna< std::vector< osg::Vec3f > >::Register(L);
	Luna< osg::BlendColor >::Register(L);
	Luna< osg::BlendEquation >::Register(L);
	Luna< osg::BlendFunc >::Register(L);
	Luna< osg::BufferIndexBinding >::Register(L);
	Luna< osg::UniformBufferBinding >::Register(L);
	Luna< osg::TransformFeedbackBufferBinding >::Register(L);
	Luna< osg::AtomicCounterBufferBinding >::Register(L);
	Luna< osg::BufferObjectProfile >::Register(L);
	Luna< osg::GLBufferObject >::Register(L);
	Luna< osg::GLBufferObject::BufferEntry >::Register(L);
	Luna< osg::GLBufferObject::Extensions >::Register(L);
	Luna< osg::GLBufferObjectSet >::Register(L);
	Luna< osg::GLBufferObjectManager >::Register(L);
	Luna< osg::BufferObject >::Register(L);
	Luna< osg::VertexBufferObject >::Register(L);
	Luna< osg::ElementBufferObject >::Register(L);
	Luna< osg::PixelBufferObject >::Register(L);
	Luna< osg::PixelDataBufferObject >::Register(L);
	Luna< osg::UniformBufferObject >::Register(L);
	Luna< osg::AtomicCounterBufferObject >::Register(L);
	Luna< osg::CullSettings >::Register(L);
	Luna< osg::Camera >::Register(L);
	Luna< std::map< osg::Camera::BufferComponent, osg::Camera::Attachment > >::Register(L);
	Luna< osg::Camera::Attachment >::Register(L);
	Luna< osg::CameraView >::Register(L);
	Luna< osg::ClampColor >::Register(L);
	Luna< osg::ClearNode >::Register(L);
	Luna< osg::ClipNode >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::ClipPlane > > >::Register(L);
	Luna< osg::ClipPlane >::Register(L);
	Luna< osg::Drawable::CullCallback >::Register(L);
	Luna< osg::ClusterCullingCallback >::Register(L);
	Luna< osg::CullStack >::Register(L);
	Luna< osg::NodeVisitor >::Register(L);
	Luna< osg::CollectOccludersVisitor >::Register(L);
	Luna< std::set< osg::ShadowVolumeOccluder > >::Register(L);
	Luna< osg::ColorMask >::Register(L);
	Luna< osg::ColorMatrix >::Register(L);
	Luna< osg::ComputeBoundsVisitor >::Register(L);
	Luna< osg::ConvexPlanarOccluder >::Register(L);
	Luna< std::vector< osg::ConvexPlanarPolygon > >::Register(L);
	Luna< osg::ConvexPlanarPolygon >::Register(L);
	Luna< osg::EllipsoidModel >::Register(L);
	Luna< osg::CoordinateSystemNode >::Register(L);
	Luna< osg::CopyOp >::Register(L);
	Luna< osg::CullFace >::Register(L);
	Luna< osg::CullingSet >::Register(L);
	Luna< std::pair< osg::ref_ptr< osg::StateSet >, osg::Polytope > >::Register(L);
	Luna< std::vector< osg::CullingSet::StateFrustumPair > >::Register(L);
	Luna< osg::CullSettings::ClampProjectionMatrixCallback >::Register(L);
	Luna< std::vector< osg::CullingSet > >::Register(L);
	Luna< osg::DeleteHandler >::Register(L);
	Luna< std::pair< unsigned int, const osg::Referenced * > >::Register(L);
	Luna< std::list< osg::DeleteHandler::FrameNumberObjectPair > >::Register(L);
	Luna< osg::Depth >::Register(L);
	Luna< osg::DisplaySettings >::Register(L);
	Luna< osg::Drawable >::Register(L);
	Luna< osg::Drawable::ComputeBoundingBoxCallback >::Register(L);
	Luna< osg::DrawPixels >::Register(L);
	Luna< osg::Fog >::Register(L);
	Luna< osg::FragmentProgram >::Register(L);
	Luna< std::map< unsigned int, osg::Vec4f > >::Register(L);
	Luna< std::map< unsigned int, osg::Matrixd > >::Register(L);
	Luna< osg::FragmentProgram::Extensions >::Register(L);
	Luna< osg::FBOExtensions >::Register(L);
	Luna< osg::RenderBuffer >::Register(L);
	Luna< osg::FrameBufferAttachment >::Register(L);
	Luna< osg::FrameBufferObject >::Register(L);
	Luna< std::map< osg::Camera::BufferComponent, osg::FrameBufferAttachment > >::Register(L);
	Luna< osg::FrameStamp >::Register(L);
	Luna< osg::FrontFace >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Drawable > > >::Register(L);
	Luna< osg::Geometry >::Register(L);
	Luna< std::vector< osg::Geometry::ArrayData > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::PrimitiveSet > > >::Register(L);
	Luna< std::vector< osg::Array * > >::Register(L);
	Luna< std::vector< osg::DrawElements * > >::Register(L);
	Luna< osg::Geometry::ArrayData >::Register(L);
	Luna< osg::GL2Extensions >::Register(L);
	Luna< osg::GLBeginEndAdapter >::Register(L);
	Luna< osg::PixelStorageModes >::Register(L);
	Luna< osg::GraphicsContext >::Register(L);
	Luna< std::vector< osg::GraphicsContext::ScreenSettings > >::Register(L);
	Luna< std::vector< osg::GraphicsContext * > >::Register(L);
	Luna< std::list< osg::ref_ptr< osg::Operation > > >::Register(L);
	Luna< std::list< osg::Camera * > >::Register(L);
	Luna< osg::ClampedLinearCostFunction1D >::Register(L);
	Luna< osg::GeometryCostEstimator >::Register(L);
	Luna< osg::TextureCostEstimator >::Register(L);
	Luna< osg::ProgramCostEstimator >::Register(L);
	Luna< osg::GraphicsCostEstimator >::Register(L);
	Luna< osg::OperationThread >::Register(L);
	Luna< osg::GraphicsThread >::Register(L);
	Luna< osg::Operation >::Register(L);
	Luna< osg::GraphicsOperation >::Register(L);
	Luna< osg::SwapBuffersOperation >::Register(L);
	Luna< osg::BarrierOperation >::Register(L);
	Luna< osg::RefBlock >::Register(L);
	Luna< osg::ReleaseContext_Block_MakeCurrentOperation >::Register(L);
	Luna< osg::BlockAndFlushOperation >::Register(L);
	Luna< osg::FlushDeletedGLObjectsOperation >::Register(L);
	Luna< osg::RunOperations >::Register(L);
	Luna< osg::State::DynamicObjectRenderingCompletedCallback >::Register(L);
	Luna< osg::EndOfDynamicDrawBlock >::Register(L);
	Luna< osg::Hint >::Register(L);
	Luna< osg::Image >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Image::DimensionsChangedCallback > > >::Register(L);
	Luna< osg::Image::DataIterator >::Register(L);
	Luna< osg::Image::DimensionsChangedCallback >::Register(L);
	Luna< osg::ImageStream >::Register(L);
	Luna< osg::ImageSequence >::Register(L);
	Luna< std::vector< osg::ImageSequence::ImageData > >::Register(L);
	Luna< osg::ImageSequence::ImageData >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::AudioStream > > >::Register(L);
	Luna< osg::Shape >::Register(L);
	Luna< osg::KdTree >::Register(L);
	Luna< std::vector< osg::KdTree::LineSegmentIntersection > >::Register(L);
	Luna< std::vector< osg::KdTree::KdNode > >::Register(L);
	Luna< std::vector< osg::KdTree::Triangle > >::Register(L);
	Luna< osg::KdTree::BuildOptions >::Register(L);
	Luna< osg::KdTree::KdNode >::Register(L);
	Luna< osg::KdTreeBuilder >::Register(L);
	Luna< osg::Light >::Register(L);
	Luna< osg::LightModel >::Register(L);
	Luna< osg::LightSource >::Register(L);
	Luna< osg::LineSegment >::Register(L);
	Luna< osg::LineStipple >::Register(L);
	Luna< osg::LineWidth >::Register(L);
	Luna< osg::LOD >::Register(L);
	Luna< std::pair< float, float > >::Register(L);
	Luna< std::vector< osg::LOD::MinMaxPair > >::Register(L);
	Luna< osg::LogicOp >::Register(L);
	Luna< osg::Material >::Register(L);
	Luna< osg::Matrixd >::Register(L);
	Luna< osg::RefMatrixd >::Register(L);
	Luna< osg::Matrixf >::Register(L);
	Luna< osg::RefMatrixf >::Register(L);
	Luna< osg::MatrixTransform >::Register(L);
	Luna< osg::Multisample >::Register(L);
	Luna< osg::Multisample::Extensions >::Register(L);
	Luna< std::vector< osg::Group * > >::Register(L);
	Luna< std::vector< std::string > >::Register(L);
	Luna< osg::Node::ComputeBoundingSphereCallback >::Register(L);
	Luna< osg::NodeTrackerCallback >::Register(L);
	Luna< osg::NodeVisitor::DatabaseRequestHandler >::Register(L);
	Luna< osg::NodeVisitor::ImageRequestHandler >::Register(L);
	Luna< osg::NodeAcceptOp >::Register(L);
	Luna< osg::NotifyHandler >::Register(L);
	Luna< osg::StandardNotifyHandler >::Register(L);
	Luna< osg::Observer >::Register(L);
	Luna< osg::ObserverSet >::Register(L);
	Luna< std::set< osg::Observer * > >::Register(L);
	Luna< osg::ObserverNodePath >::Register(L);
	Luna< osg::OccluderNode >::Register(L);
	Luna< osg::TestResult >::Register(L);
	Luna< osg::QueryGeometry >::Register(L);
	Luna< osg::OcclusionQueryNode >::Register(L);
	Luna< osg::RefBlockCount >::Register(L);
	Luna< osg::OperationQueue >::Register(L);
	Luna< std::set< osg::OperationThread * > >::Register(L);
	Luna< osg::PagedLOD >::Register(L);
	Luna< std::vector< osg::PagedLOD::PerRangeData > >::Register(L);
	Luna< osg::Plane >::Register(L);
	Luna< osg::Point >::Register(L);
	Luna< osg::Point::Extensions >::Register(L);
	Luna< osg::PointSprite >::Register(L);
	Luna< osg::PolygonMode >::Register(L);
	Luna< osg::PolygonOffset >::Register(L);
	Luna< osg::PolygonStipple >::Register(L);
	Luna< osg::Polytope >::Register(L);
	Luna< osg::fast_back_stack< unsigned int > >::Register(L);
	Luna< osg::Polytope::PlaneList >::Register(L);
	Luna< osg::PositionAttitudeTransform >::Register(L);
	Luna< osg::PrimitiveSet >::Register(L);
	Luna< osg::DrawArrays >::Register(L);
	Luna< osg::DrawArrayLengths >::Register(L);
	Luna< osg::DrawElements >::Register(L);
	Luna< osg::DrawElementsUByte >::Register(L);
	Luna< osg::DrawElementsUShort >::Register(L);
	Luna< osg::DrawElementsUInt >::Register(L);
	Luna< osg::Program >::Register(L);
	Luna< std::map< std::string, unsigned int > >::Register(L);
	Luna< std::map< unsigned int, osg::Program::ActiveVarInfo > >::Register(L);
	Luna< std::map< std::string, osg::Program::ActiveVarInfo > >::Register(L);
	Luna< std::map< std::string, osg::Program::UniformBlockInfo > >::Register(L);
	Luna< osg::Program::ActiveVarInfo >::Register(L);
	Luna< osg::Program::PerContextProgram >::Register(L);
	Luna< osg::Projection >::Register(L);
	Luna< osg::ProxyNode >::Register(L);
	Luna< osg::Quat >::Register(L);
	Luna< osg::RenderInfo >::Register(L);
	Luna< osg::SampleMaski >::Register(L);
	Luna< osg::SampleMaski::Extensions >::Register(L);
	Luna< osg::Scissor >::Register(L);
	Luna< osg::Sequence >::Register(L);
	Luna< osg::ShadeModel >::Register(L);
	Luna< osg::ShaderBinary >::Register(L);
	Luna< osg::Shader >::Register(L);
	Luna< std::multimap< float, std::string > >::Register(L);
	Luna< osg::Shader::PerContextShader >::Register(L);
	Luna< osg::ShaderComponent >::Register(L);
	Luna< osg::ShaderAttribute >::Register(L);
	Luna< osg::ShaderComposer >::Register(L);
	Luna< std::vector< const osg::Shader * > >::Register(L);
	Luna< osg::ShadowVolumeOccluder >::Register(L);
	Luna< std::vector< osg::Polytope > >::Register(L);
	Luna< osg::ShapeVisitor >::Register(L);
	Luna< osg::ConstShapeVisitor >::Register(L);
	Luna< osg::Sphere >::Register(L);
	Luna< osg::Box >::Register(L);
	Luna< osg::Cone >::Register(L);
	Luna< osg::Cylinder >::Register(L);
	Luna< osg::Capsule >::Register(L);
	Luna< osg::InfinitePlane >::Register(L);
	Luna< osg::TriangleMesh >::Register(L);
	Luna< osg::ConvexHull >::Register(L);
	Luna< osg::HeightField >::Register(L);
	Luna< osg::CompositeShape >::Register(L);
	Luna< std::vector< osg::ref_ptr< osg::Shape > > >::Register(L);
	Luna< osg::TessellationHints >::Register(L);
	Luna< osg::ShapeDrawable >::Register(L);
	Luna< osg::VertexAttribAlias >::Register(L);
	Luna< osg::State >::Register(L);
	Luna< std::pair< osg::StateAttribute::Type, unsigned int > >::Register(L);
	Luna< std::vector< osg::StateSet * > >::Register(L);
	Luna< osg::StateAttribute::ModeUsage >::Register(L);
	Luna< osg::StateSet >::Register(L);
	Luna< std::vector< osg::Object * > >::Register(L);
	Luna< std::map< unsigned int, unsigned int > >::Register(L);
	Luna< std::pair< osg::ref_ptr< osg::StateAttribute >, unsigned int > >::Register(L);
	Luna< std::map< osg::StateAttribute::TypeMemberPair, osg::StateSet::RefAttributePair > >::Register(L);
	Luna< std::vector< osg::StateSet::ModeList > >::Register(L);
	Luna< std::vector< osg::StateSet::AttributeList > >::Register(L);
	Luna< std::pair< osg::ref_ptr< osg::Uniform >, unsigned int > >::Register(L);
	Luna< std::map< std::string, osg::StateSet::RefUniformPair > >::Register(L);
	Luna< osg::StateSet::Callback >::Register(L);
	Luna< osg::Stats >::Register(L);
	Luna< std::map< std::string, double > >::Register(L);
	Luna< std::vector< osg::Stats::AttributeMap > >::Register(L);
	Luna< std::map< std::string, bool > >::Register(L);
	Luna< osg::Stencil >::Register(L);
	Luna< osg::Stencil::Extensions >::Register(L);
	Luna< osg::StencilTwoSided >::Register(L);
	Luna< osg::StencilTwoSided::Extensions >::Register(L);
	Luna< osg::Switch >::Register(L);
	Luna< std::vector< bool > >::Register(L);
	Luna< osg::TexEnv >::Register(L);
	Luna< osg::TexEnvCombine >::Register(L);
	Luna< osg::TexEnvFilter >::Register(L);
	Luna< osg::TexGen >::Register(L);
	Luna< osg::TexGenNode >::Register(L);
	Luna< osg::TexMat >::Register(L);
	Luna< osg::Texture >::Register(L);
	Luna< std::list< osg::ref_ptr< osg::Texture::TextureObject > > >::Register(L);
	Luna< osg::Texture::Extensions >::Register(L);
	Luna< osg::Texture::ImageAttachment >::Register(L);
	Luna< osg::Texture1D >::Register(L);
	Luna< osg::Texture1D::SubloadCallback >::Register(L);
	Luna< osg::Texture2D >::Register(L);
	Luna< osg::Texture2D::SubloadCallback >::Register(L);
	Luna< osg::Texture2DArray >::Register(L);
	Luna< osg::Texture2DArray::Extensions >::Register(L);
	Luna< osg::Texture2DArray::SubloadCallback >::Register(L);
	Luna< osg::Texture2DMultisample >::Register(L);
	Luna< osg::Texture3D >::Register(L);
	Luna< osg::Texture3D::Extensions >::Register(L);
	Luna< osg::Texture3D::SubloadCallback >::Register(L);
	Luna< osg::TextureCubeMap >::Register(L);
	Luna< osg::TextureCubeMap::Extensions >::Register(L);
	Luna< osg::TextureCubeMap::SubloadCallback >::Register(L);
	Luna< osg::TextureRectangle >::Register(L);
	Luna< osg::TextureRectangle::SubloadCallback >::Register(L);
	Luna< osg::Timer >::Register(L);
	Luna< osg::ElapsedTime >::Register(L);
	Luna< osg::TransferFunction >::Register(L);
	Luna< osg::TransferFunction1D >::Register(L);
	Luna< std::map< float, osg::Vec4f > >::Register(L);
	Luna< osg::Uniform >::Register(L);
	Luna< osg::Uniform::Callback >::Register(L);
	Luna< osg::UserDataContainer >::Register(L);
	Luna< osg::DefaultUserDataContainer >::Register(L);
	Luna< osg::ValueObject >::Register(L);
	Luna< osg::ValueObject::GetValueVisitor >::Register(L);
	Luna< osg::ValueObject::SetValueVisitor >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< std::string > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< bool > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< char > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< unsigned char > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< short > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< unsigned short > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< int > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< unsigned int > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< float > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< double > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec2f > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec3f > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec4f > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec2d > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec3d > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Vec4d > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Quat > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Plane > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Matrixf > >::Register(L);
	Luna< osg::ValueObjectClassNameTrait< Matrixd > >::Register(L);
	Luna< osg::Vec2b >::Register(L);
	Luna< osg::Vec2d >::Register(L);
	Luna< osg::Vec2f >::Register(L);
	Luna< osg::Vec2s >::Register(L);
	Luna< osg::Vec3b >::Register(L);
	Luna< osg::Vec3d >::Register(L);
	Luna< osg::Vec3f >::Register(L);
	Luna< osg::Vec3s >::Register(L);
	Luna< osg::Vec4b >::Register(L);
	Luna< osg::Vec4d >::Register(L);
	Luna< osg::Vec4f >::Register(L);
	Luna< osg::Vec4s >::Register(L);
	Luna< osg::Vec4ub >::Register(L);
	Luna< osg::VertexProgram >::Register(L);
	Luna< osg::VertexProgram::Extensions >::Register(L);
	Luna< osg::View >::Register(L);
	Luna< osg::View::Slave >::Register(L);
	Luna< osg::Viewport >::Register(L);
	Luna< osg::ref_ptr< osg::Array > >::Register(L);
	Luna< osg::ref_ptr< osg::Image > >::Register(L);
	Luna< osg::ref_ptr< osg::PrimitiveSet > >::Register(L);
	Luna< osg::ref_ptr< osg::AnimationPath > >::Register(L);
	Luna< osg::Vec2Array >::Register(L);
	Luna< osg::Vec3Array >::Register(L);
	Luna< osg::Vec4Array >::Register(L);
	Luna< osg::MatrixList >::Register(L);
	Luna< osg::NodePath >::Register(L);
	Luna< osg::NodePathList >::Register(L);
	Luna< osg::Matrix3 >::Register(L);
	Luna< osg::Matrix3d >::Register(L);
	Luna< osg::Vec2dVector >::Register(L);
	Luna< osg::Vec3dVector >::Register(L);
	Luna< osg::Vec4dVector >::Register(L);
	Luna< std::deque< std::string > >::Register(L);
	Luna< std::list< std::string > >::Register(L);
	Luna< std::list< osg::ref_ptr< osgDB::ReaderWriterInfo > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ReaderWriter >::Register(L);
	Luna< osgDB::Archive >::Register(L);
	Luna< osgDB::AuthenticationDetails >::Register(L);
	Luna< osgDB::AuthenticationMap >::Register(L);
	Luna< osgDB::FindFileCallback >::Register(L);
	Luna< osgDB::ReadFileCallback >::Register(L);
	Luna< osgDB::WriteFileCallback >::Register(L);
	Luna< osgDB::FileLocationCallback >::Register(L);
	Luna< osgDB::DatabasePager >::Register(L);
	Luna< osgDB::FileList >::Register(L);
	Luna< osgDB::DatabaseRevision >::Register(L);
	Luna< osgDB::DatabaseRevisions >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgDB::DatabaseRevision > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ObjectGLenum >::Register(L);
	Luna< osgDB::ObjectProperty >::Register(L);
	Luna< osgDB::ObjectMark >::Register(L);
	Luna< osgDB::DotOsgWrapper >::Register(L);
	Luna< osgDB::DeprecatedDotOsgWrapperManager >::Register(L);
	Luna< osgDB::RegisterDotOsgWrapperProxy >::Register(L);
	Luna< osgDB::DynamicLibrary >::Register(L);
	Luna< osgDB::ExternalFileWriter >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< const osg::Object *, osgDB::ExternalFileWriter::ObjectData > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::FileCache >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::list< osg::ref_ptr< osgDB::DatabaseRevisions > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::FileNameComparator >::Register(L);
	Luna< osgDB::fstream >::Register(L);
	Luna< osgDB::ifstream >::Register(L);
	Luna< osgDB::ofstream >::Register(L);
	Luna< osgDB::Options >::Register(L);
	Luna< osgDB::ImageOptions >::Register(L);
	Luna< osgDB::ImagePager >::Register(L);
	Luna< osgDB::ImageProcessor >::Register(L);
	Luna< osgDB::basic_type_wrapper >::Register(L);
	Luna< osgDB::Field >::Register(L);
	Luna< osgDB::FieldReader >::Register(L);
	Luna< osgDB::FieldReaderIterator >::Register(L);
	Luna< osgDB::Input >::Register(L);
	Luna< osgDB::InputException >::Register(L);
	Luna< osgDB::InputStream >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< unsigned int, osg::ref_ptr< osg::Array > > >::Register(L);
	Luna< std::map< unsigned int, osg::ref_ptr< osg::Object > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::BaseCompressor >::Register(L);
	Luna< osgDB::FinishedObjectReadCallback >::Register(L);
	Luna< osgDB::ObjectWrapper >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgDB::BaseSerializer > > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osgDB::FinishedObjectReadCallback > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::UpdateWrapperVersionProxy >::Register(L);
	Luna< osgDB::ObjectWrapperManager >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< std::string, osg::ref_ptr< osgDB::ObjectWrapper > > >::Register(L);
	Luna< std::map< std::string, osg::ref_ptr< osgDB::BaseCompressor > > >::Register(L);
	Luna< std::map< std::string, osgDB::IntLookup > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::RegisterWrapperProxy >::Register(L);
	Luna< osgDB::RegisterCompressorProxy >::Register(L);
	Luna< osgDB::Output >::Register(L);
	Luna< osgDB::OutputException >::Register(L);
	Luna< osgDB::OutputStream >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< const osg::Array *, unsigned int > >::Register(L);
	Luna< std::map< const osg::Object *, unsigned int > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::ParameterOutput >::Register(L);
	Luna< osgDB::ReaderWriterInfo >::Register(L);
	Luna< osgDB::Registry >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgDB::ReaderWriter > > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osgDB::ImageProcessor > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::PluginFunctionProxy >::Register(L);
	Luna< osgDB::IntLookup >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< int, std::string > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::UserLookupTableProxy >::Register(L);
	Luna< osgDB::BaseSerializer >::Register(L);
	Luna< osgDB::SharedStateManager >::Register(L);
	Luna< osgDB::OutputIterator >::Register(L);
	Luna< osgDB::InputIterator >::Register(L);
	Luna< osgDB::XmlNode >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgDB::XmlNode > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgDB");
	Luna< osgDB::XmlNode::ControlMap >::Register(L);
	Luna< osgDB::XmlNode::Input >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::GUIEventHandler >::Register(L);
	Luna< osgGA::CameraManipulator >::Register(L);
	Luna< osgGA::AnimationPathManipulator >::Register(L);
	Luna< osgGA::AnimationPathManipulator::AnimationCompletedCallback >::Register(L);
	Luna< osgGA::CameraViewSwitchManipulator >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osg::CameraView > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::Device >::Register(L);
	Luna< osgGA::DriveManipulator >::Register(L);
	Luna< osgGA::EventQueue >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::list< osg::ref_ptr< osgGA::GUIEventAdapter > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::EventVisitor >::Register(L);
	Luna< osgGA::StandardManipulator >::Register(L);
	Luna< osgGA::FirstPersonManipulator >::Register(L);
	Luna< osgGA::FlightManipulator >::Register(L);
	Luna< osgGA::GUIActionAdapter >::Register(L);
	Luna< osgGA::GUIEventAdapter >::Register(L);
	Luna< osgGA::GUIEventHandlerVisitor >::Register(L);
	Luna< osgGA::KeySwitchMatrixManipulator >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::pair< std::string, osg::ref_ptr< osgGA::CameraManipulator > > >::Register(L);
	Luna< std::map< int, osgGA::KeySwitchMatrixManipulator::NamedManipulator > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgGA");
	Luna< osgGA::OrbitManipulator >::Register(L);
	Luna< osgGA::TrackballManipulator >::Register(L);
	Luna< osgGA::MultiTouchTrackballManipulator >::Register(L);
	Luna< osgGA::NodeTrackerManipulator >::Register(L);
	Luna< osgGA::SphericalManipulator >::Register(L);
	Luna< osgGA::StateSetManipulator >::Register(L);
	Luna< osgGA::TerrainManipulator >::Register(L);
	Luna< osgGA::UFOManipulator >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< osgParticle::range< float > >::Register(L);
	Luna< osgParticle::range< osg::Vec2f > >::Register(L);
	Luna< osgParticle::range< osg::Vec3f > >::Register(L);
	Luna< osgParticle::range< osg::Vec4f > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgParticle");
	Luna< osgParticle::Operator >::Register(L);
	Luna< osgParticle::AccelOperator >::Register(L);
	Luna< osgParticle::AngularAccelOperator >::Register(L);
	Luna< osgParticle::AngularDampingOperator >::Register(L);
	Luna< osgParticle::DomainOperator >::Register(L);
	Luna< osgParticle::BounceOperator >::Register(L);
	Luna< osgParticle::Placer >::Register(L);
	Luna< osgParticle::CenteredPlacer >::Register(L);
	Luna< osgParticle::BoxPlacer >::Register(L);
	Luna< osgParticle::CompositePlacer >::Register(L);
	Luna< osgParticle::ParticleSystem >::Register(L);
	Luna< osgParticle::ConnectedParticleSystem >::Register(L);
	Luna< osgParticle::Counter >::Register(L);
	Luna< osgParticle::ConstantRateCounter >::Register(L);
	Luna< osgParticle::DampingOperator >::Register(L);
	Luna< osgParticle::DomainOperator::Domain >::Register(L);
	Luna< osgParticle::ParticleProcessor >::Register(L);
	Luna< osgParticle::Emitter >::Register(L);
	Luna< osgParticle::ParticleEffect >::Register(L);
	Luna< osgParticle::ExplosionDebrisEffect >::Register(L);
	Luna< osgParticle::ExplosionEffect >::Register(L);
	Luna< osgParticle::ExplosionOperator >::Register(L);
	Luna< osgParticle::FireEffect >::Register(L);
	Luna< osgParticle::FluidFrictionOperator >::Register(L);
	Luna< osgParticle::Program >::Register(L);
	Luna< osgParticle::FluidProgram >::Register(L);
	Luna< osgParticle::ForceOperator >::Register(L);
	Luna< osgParticle::Interpolator >::Register(L);
	Luna< osgParticle::LinearInterpolator >::Register(L);
	Luna< osgParticle::ModularEmitter >::Register(L);
	Luna< osgParticle::ModularProgram >::Register(L);
	Luna< osgParticle::MultiSegmentPlacer >::Register(L);
	Luna< osgParticle::OrbitOperator >::Register(L);
	Luna< osgParticle::Particle >::Register(L);
	Luna< osgParticle::ParticleSystemUpdater >::Register(L);
	Luna< osgParticle::PointPlacer >::Register(L);
	Luna< osgParticle::PrecipitationEffect >::Register(L);
	Luna< osgParticle::PrecipitationEffect::PrecipitationDrawable >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< osgParticle::PrecipitationEffect::PrecipitationDrawable::Cell, osgParticle::PrecipitationEffect::PrecipitationDrawable::DepthMatrixStartTime > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgParticle");
	Luna< osgParticle::PrecipitationEffect::PrecipitationDrawable::Cell >::Register(L);
	Luna< osgParticle::PrecipitationEffect::PrecipitationDrawable::DepthMatrixStartTime >::Register(L);
	Luna< osgParticle::Shooter >::Register(L);
	Luna< osgParticle::RadialShooter >::Register(L);
	Luna< osgParticle::VariableRateCounter >::Register(L);
	Luna< osgParticle::RandomRateCounter >::Register(L);
	Luna< osgParticle::SectorPlacer >::Register(L);
	Luna< osgParticle::SegmentPlacer >::Register(L);
	Luna< osgParticle::SinkOperator >::Register(L);
	Luna< osgParticle::SmokeEffect >::Register(L);
	Luna< osgParticle::SmokeTrailEffect >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::pair< unsigned int, unsigned int > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgText");
	Luna< osgText::TextBase >::Register(L);
	Luna< osgText::Text >::Register(L);
	Luna< osgText::FadeText >::Register(L);
	Luna< osgText::Font >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgText::GlyphTexture > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgText");
	Luna< osgText::Glyph >::Register(L);
	Luna< osgText::GlyphGeometry >::Register(L);
	Luna< osgText::Glyph3D >::Register(L);
	Luna< osgText::GlyphTexture >::Register(L);
	Luna< osgText::String >::Register(L);
	Luna< osgText::Bevel >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::Vec2f > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgText");
	Luna< osgText::Style >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< osg::ref_ptr< osgText::GlyphTexture >, osgText::Text::GlyphQuads > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgText");
	Luna< osgText::Text::GlyphQuads >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osgText::Glyph * > >::Register(L);
	Luna< std::vector< osg::Vec4f > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgText");
	Luna< osgText::Text3D >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::CubeMapGenerator >::Register(L);
	Luna< osgUtil::CullVisitor >::Register(L);
	Luna< osgUtil::DelaunayConstraint >::Register(L);
	Luna< osgUtil::DelaunayTriangulator >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgUtil::DelaunayConstraint > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::DisplayRequirementsVisitor >::Register(L);
	Luna< osgUtil::DrawElementTypeSimplifier >::Register(L);
	Luna< osgUtil::DrawElementTypeSimplifierVisitor >::Register(L);
	Luna< osgUtil::dereference_less >::Register(L);
	Luna< osgUtil::dereference_clear >::Register(L);
	Luna< osgUtil::EdgeCollector >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::list< osg::ref_ptr< osg::UIntArray > > >::Register(L);
	Luna< std::set< osg::ref_ptr< osgUtil::EdgeCollector::Edge >, osgUtil::dereference_less > >::Register(L);
	Luna< std::list< osg::ref_ptr< osgUtil::EdgeCollector::Edgeloop > > >::Register(L);
	Luna< std::set< osg::ref_ptr< osgUtil::EdgeCollector::Point >, osgUtil::dereference_less > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osgUtil::EdgeCollector::Point > > >::Register(L);
	Luna< std::list< osg::ref_ptr< osgUtil::EdgeCollector::Triangle > > >::Register(L);
	Luna< std::set< osg::ref_ptr< osgUtil::EdgeCollector::Triangle > > >::Register(L);
	Luna< std::map< osg::ref_ptr< osgUtil::EdgeCollector::Triangle >, unsigned int, osgUtil::dereference_less > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::EdgeCollector::Edge >::Register(L);
	Luna< osgUtil::GLObjectsVisitor >::Register(L);
	Luna< osgUtil::GLObjectsOperation >::Register(L);
	Luna< osgUtil::HalfWayMapGenerator >::Register(L);
	Luna< osgUtil::HighlightMapGenerator >::Register(L);
	Luna< osgUtil::StateToCompile >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::set< osg::Drawable * > >::Register(L);
	Luna< std::set< osg::StateSet * > >::Register(L);
	Luna< std::set< osg::Texture * > >::Register(L);
	Luna< std::set< osg::Program * > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IncrementalCompileOperation >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::set< osg::GraphicsContext * > >::Register(L);
	Luna< std::list< osg::ref_ptr< osgUtil::IncrementalCompileOperation::CompileSet > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IncrementalCompileOperation::CompileCompletedCallback >::Register(L);
	Luna< osgUtil::IncrementalCompileOperation::CompileOp >::Register(L);
	Luna< osgUtil::IncrementalCompileOperation::CompileDrawableOp >::Register(L);
	Luna< osgUtil::IncrementalCompileOperation::CompileInfo >::Register(L);
	Luna< osgUtil::IncrementalCompileOperation::CompileList >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::list< osg::ref_ptr< osgUtil::IncrementalCompileOperation::CompileOp > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IncrementalCompileOperation::CompileProgramOp >::Register(L);
	Luna< osgUtil::IncrementalCompileOperation::CompileSet >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< osg::GraphicsContext *, osgUtil::IncrementalCompileOperation::CompileList > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IncrementalCompileOperation::CompileTextureOp >::Register(L);
	Luna< osgUtil::Intersector >::Register(L);
	Luna< osgUtil::IntersectorGroup >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::ref_ptr< osgUtil::Intersector > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IntersectionVisitor >::Register(L);
	Luna< osgUtil::Hit >::Register(L);
	Luna< osgUtil::IntersectVisitor >::Register(L);
	Luna< osgUtil::PickVisitor >::Register(L);
	Luna< osgUtil::LineSegmentIntersector >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::multiset< osgUtil::LineSegmentIntersector::Intersection > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::LineSegmentIntersector::Intersection >::Register(L);
	Luna< osgUtil::BaseOptimizerVisitor >::Register(L);
	Luna< osgUtil::GeometryCollector >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::set< osg::Geometry * > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::IndexMeshVisitor >::Register(L);
	Luna< osgUtil::VertexCacheVisitor >::Register(L);
	Luna< osgUtil::VertexCacheMissVisitor >::Register(L);
	Luna< osgUtil::VertexAccessOrderVisitor >::Register(L);
	Luna< osgUtil::AddRangeOperator >::Register(L);
	Luna< osgUtil::MultiplyRangeOperator >::Register(L);
	Luna< osgUtil::Optimizer >::Register(L);
	Luna< osgUtil::PerlinNoise >::Register(L);
	Luna< osgUtil::PlaneIntersector >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osgUtil::PlaneIntersector::Intersection > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::PlaneIntersector::Intersection >::Register(L);
	Luna< osgUtil::PolytopeIntersector >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::set< osgUtil::PolytopeIntersector::Intersection > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::PolytopeIntersector::Intersection >::Register(L);
	Luna< osgUtil::PositionalStateContainer >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::pair< osg::ref_ptr< const osg::StateAttribute >, osg::ref_ptr< osg::RefMatrixd > > >::Register(L);
	Luna< std::vector< osgUtil::PositionalStateContainer::AttrMatrixPair > >::Register(L);
	Luna< std::map< unsigned int, osgUtil::PositionalStateContainer::AttrMatrixList > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::PrintVisitor >::Register(L);
	Luna< osgUtil::ReflectionMapGenerator >::Register(L);
	Luna< osgUtil::RenderBin >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osgUtil::RenderLeaf * > >::Register(L);
	Luna< std::vector< osgUtil::StateGraph * > >::Register(L);
	Luna< std::map< int, osg::ref_ptr< osgUtil::RenderBin > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::RenderBin::DrawCallback >::Register(L);
	Luna< osgUtil::RenderLeaf >::Register(L);
	Luna< osgUtil::RenderStage >::Register(L);
	Luna< osgUtil::RenderStage::Attachment >::Register(L);
	Luna< osgUtil::SceneGraphBuilder >::Register(L);
	Luna< osgUtil::SceneView >::Register(L);
	Luna< osgUtil::SceneView::ComputeStereoMatricesCallback >::Register(L);
	Luna< osgUtil::ShaderGenCache >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< int, osg::ref_ptr< osg::StateSet > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::ShaderGenVisitor >::Register(L);
	Luna< osgUtil::Simplifier >::Register(L);
	Luna< osgUtil::Simplifier::ContinueSimplificationCallback >::Register(L);
	Luna< osgUtil::SmoothingVisitor >::Register(L);
	Luna< osgUtil::StateGraph >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< const osg::StateSet *, osg::ref_ptr< osgUtil::StateGraph > > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osgUtil::RenderLeaf > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::Statistics >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::map< unsigned int, osgUtil::Statistics::PrimitivePair > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::StatsVisitor >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::set< osg::Node * > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgUtil");
	Luna< osgUtil::TangentSpaceGenerator >::Register(L);
	Luna< osgUtil::Tessellator >::Register(L);
	Luna< osgUtil::TransformCallback >::Register(L);
	Luna< osgUtil::TriStripVisitor >::Register(L);
	Luna< osgUtil::UpdateVisitor >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgViewer");
	Luna< osgViewer::ViewerBase >::Register(L);
	Luna< osgViewer::CompositeViewer >::Register(L);
	Luna< osgViewer::GraphicsWindow >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::list< osgViewer::View * > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgViewer");
	Luna< osgViewer::GraphicsWindowEmbedded >::Register(L);
	Luna< osgViewer::GraphicsWindowFunctionProxy >::Register(L);
	Luna< osgViewer::OpenGLQuerySupport >::Register(L);
	Luna< osgViewer::Renderer >::Register(L);
	Luna< osgViewer::Scene >::Register(L);
	Luna< osgViewer::DepthPartitionSettings >::Register(L);
	Luna< osgViewer::View >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::list< osg::ref_ptr< osgGA::GUIEventHandler > > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgViewer");
	Luna< osgViewer::Viewer >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::Camera * > >::Register(L);
	Luna< std::vector< osgViewer::GraphicsWindow * > >::Register(L);
	Luna< std::vector< OpenThreads::Thread * > >::Register(L);
	Luna< std::vector< osg::OperationThread * > >::Register(L);
	Luna< std::vector< osgViewer::Scene * > >::Register(L);
	Luna< std::vector< osgViewer::View * > >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osgViewer");
	Luna< osgViewer::HelpHandler >::Register(L);
	Luna< osgViewer::StatsHandler >::Register(L);
	Luna< osgViewer::WindowSizeHandler >::Register(L);
	Luna< osgViewer::ThreadingHandler >::Register(L);
	Luna< osgViewer::RecordCameraPathHandler >::Register(L);
	Luna< osgViewer::LODScaleHandler >::Register(L);
	Luna< osgViewer::ToggleSyncToVBlankHandler >::Register(L);
	Luna< osgViewer::ScreenCaptureHandler >::Register(L);
	Luna< osgViewer::InteractiveImageHandler >::Register(L);
	luna_popModule(L);
	luna_pushModule(L,"osg");
	Luna< std::vector< osg::VertexAttribAlias > >::Register(L);
	Luna< std::vector< osg::State::AttributePair > >::Register(L);
	Luna< std::vector< osgUtil::Hit > >::Register(L);
	Luna< std::map< const osg::LineSegment *, osgUtil::IntersectVisitor::HitList > >::Register(L);
	Luna< std::vector< osg::ref_ptr< osgUtil::Tessellator::Prim > > >::Register(L);
	luna_popModule(L);

	luna_pushModule(L,"osg");

	register_defines(L);

	register_enums(L);

	luna_popModule(L);

	register_global_functions(L);

	luna_copyParents(L,"osg");
	luna_copyParents(L,"osgGA");
	luna_copyParents(L,"osgUtil");
	luna_copyParents(L,"osgText");
	luna_copyParents(L,"osgDB");
	luna_copyParents(L,"osgViewer");
	luna_copyParents(L,"OpenThreads");
	luna_copyParents(L,"osgParticle");

	luna_pushModule(L,"osg");
	return 1;
}

#ifdef __cplusplus
}
#endif

